export const LANG = {
  en: {
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Log Out',
    phone: 'Mobile Number',
    password: 'Password',
    role: 'Select Your Role',
    worker: 'Worker (Get Jobs)',
    employer: 'Employer (Hire Workers)',
    admin: 'Admin',
    noAccount: 'Don\'t have an account?',
    haveAccount: 'Already have an account?',
    greeting: 'Good morning 👋',
    title: 'Find Work.<br>Get Paid.',
    sub: 'Connect workers with employers. Fast, simple, trusted.',
    stat1: 'Workers',
    stat2: 'Jobs',
    stat3: 'Rating',
    choose: 'WHAT DO YOU WANT TO DO?',
    btn1: 'Find a Worker',
    btn1s: 'Plumber, Electrician, Painter…',
    btn2: 'I am a Worker',
    btn2s: 'Register and find work near you',
    btn3: 'Post a Job',
    btn3s: 'Tell us what work you need done',
    btn4: 'Ask AI Helper',
    btn4s: 'Get help, advice, wage info',
    nav1: 'HOME',
    nav2: 'WORKERS',
    nav3: 'POST JOB',
    nav4: 'AI HELP',
    nav5: 'PROFILE',
    fwTitle: 'Find Workers',
    regTitle: 'Register as Worker',
    regBtn: '✅ Register Now',
    regLblName: '👤 Your Full Name',
    regLblPhone: '📞 Mobile Number',
    regLblTrade: '🛠 Your Trade / Skill',
    regLblExp: '📅 Experience (years)',
    regLblArea: '📍 Your Area / Location',
    regLblWage: '💰 Daily Wage (₹)',
    regLblLang: '🗣 Languages You Speak',
    pjTitle: 'Post a Job',
    pjLblTitle: '📋 Job Title',
    pjLblTrade: '🛠 Trade Needed',
    pjLblDesc: '📝 Describe the Work',
    pjLblLoc: '📍 Location',
    pjLblWage: '💰 Wage Offered (₹/day)',
    pjLblPhone: '📞 Contact Number',
    pjLblUrgent: '🔴 Is this urgent?',
    aiTitle: '🤖 AI Helper',
    aiIntro: 'Ask me anything — wage rates, worker rights, how to find work, documents needed…',
    aiQuickLbl: 'QUICK QUESTIONS',
    mpTitle: 'My Profile',
    voiceSpeak: 'Speak to fill form',
    voiceListening: '🔴 Listening… speak now',
    wagePer: 'per day',
    callBtn: '📞 Call Now',
    hireBtn: '✅ Apply / Hire Now',
    appliedBtn: 'Applied',
    applyBtn: 'Apply for Job',
    availNow: 'Available Now',
    availSoon: 'Tomorrow',
    availBusy: 'Busy',
    verified: '✓ Verified',
    quickQs: [
      'What is the minimum wage for a plumber?',
      'How do I get Aadhaar card?',
      'What documents do I need to register?',
      'How do I report non-payment of wages?',
    ]
  },
  hi: {
    login: 'लॉगिन करें',
    signup: 'पंजीकरण करें',
    logout: 'लॉग आउट',
    phone: 'मोबाइल नंबर',
    password: 'पासवर्ड',
    role: 'अपनी भूमिका चुनें',
    worker: 'कामगार (काम पाएं)',
    employer: 'नियोक्ता (काम दें)',
    admin: 'एडमिन',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से खाता है?',
    greeting: 'सुप्रभात 👋',
    title: 'काम खोजें।<br>पैसे पाएं।',
    sub: 'मजदूरों को नियोक्ताओं से जोड़ें। तेज़, सरल, भरोसेमंद।',
    stat1: 'कामगार',
    stat2: 'नौकरियां',
    stat3: 'रेटिंग',
    choose: 'आप क्या करना चाहते हैं?',
    btn1: 'कामगार खोजें',
    btn1s: 'प्लंबर, इलेक्ट्रीशियन, पेंटर…',
    btn2: 'मैं कामगार हूं',
    btn2s: 'रजिस्टर करें और काम पाएं',
    btn3: 'काम पोस्ट करें',
    btn3s: 'बताएं आपको क्या काम चाहिए',
    btn4: 'AI से पूछें',
    btn4s: 'मदद, सलाह, मजदूरी जानकारी',
    nav1: 'होम',
    nav2: 'कामगार',
    nav3: 'काम',
    nav4: 'AI मदद',
    nav5: 'प्रोफाइल',
    fwTitle: 'कामगार खोजें',
    regTitle: 'कामगार के रूप में रजिस्टर करें',
    regBtn: '✅ अभी रजिस्टर करें',
    regLblName: '👤 आपका पूरा नाम',
    regLblPhone: '📞 मोबाइल नंबर',
    regLblTrade: '🛠 आपका काम / हुनर',
    regLblExp: '📅 अनुभव (साल)',
    regLblArea: '📍 आपका इलाका',
    regLblWage: '💰 दैनिक मजदूरी (₹)',
    regLblLang: '🗣 भाषाएं जो आप बोलते हैं',
    pjTitle: 'काम पोस्ट करें',
    pjLblTitle: '📋 काम का शीर्षक',
    pjLblTrade: '🛠 किस काम की जरूरत है',
    pjLblDesc: '📝 काम का विवरण',
    pjLblLoc: '📍 जगह',
    pjLblWage: '💰 मजदूरी (₹/दिन)',
    pjLblPhone: '📞 आपका नंबर',
    pjLblUrgent: '🔴 क्या यह जरूरी है?',
    aiTitle: '🤖 AI सहायक',
    aiIntro: 'कुछ भी पूछें — मजदूरी, अधिकार, काम कैसे खोजें, कौन से कागज चाहिए…',
    aiQuickLbl: 'जल्दी सवाल',
    mpTitle: 'मेरा प्रोफाइल',
    voiceSpeak: 'बोलकर फॉर्म भरें',
    voiceListening: '🔴 सुन रहा हूं… बोलें',
    wagePer: 'प्रति दिन',
    callBtn: '📞 कॉल करें',
    hireBtn: '✅ काम दें',
    appliedBtn: 'आवेदन किया',
    applyBtn: 'काम के लिए आवेदन करें',
    availNow: 'अभी उपलब्ध',
    availSoon: 'कल से',
    availBusy: 'व्यस्त',
    verified: '✓ सत्यापित',
    quickQs: [
      'प्लंबर की न्यूनतम मजदूरी क्या है?',
      'आधार कार्ड कैसे बनवाएं?',
      'रजिस्टर के लिए कौन से कागज चाहिए?',
      'मजदूरी न मिले तो क्या करें?',
    ]
  },
  mr: {
    login: 'लॉगिन करा',
    signup: 'नोंदणी करा',
    logout: 'लॉग आउट',
    phone: 'मोबाइल नंबर',
    password: 'पासवर्ड',
    role: 'भूमिका निवडा',
    worker: 'कामगार (काम मिळवा)',
    employer: 'नियोक्ता (काम द्या)',
    admin: 'एडमिन',
    noAccount: 'खाते नाही का?',
    haveAccount: 'आधीच खाते आहे का?',
    greeting: 'सुप्रभात 👋',
    title: 'काम शोधा।<br>पैसे मिळवा।',
    sub: 'कामगारांना मालकांशी जोडा. जलद, सोपे, विश्वासू.',
    stat1: 'कामगार',
    stat2: 'कामे',
    stat3: 'रेटिंग',
    choose: 'तुम्हाला काय करायचे आहे?',
    btn1: 'कामगार शोधा',
    btn1s: 'प्लंबर, इलेक्ट्रिशियन, पेंटर…',
    btn2: 'मी कामगार आहे',
    btn2s: 'नोंदणी करा आणि काम मिळवा',
    btn3: 'काम पोस्ट करा',
    btn3s: 'तुम्हाला काय काम हवे ते सांगा',
    btn4: 'AI ला विचारा',
    btn4s: 'मदत, सल्ला, मजुरी माहिती',
    nav1: 'मुख्यपृष्ठ',
    nav2: 'कामगार',
    nav3: 'काम',
    nav4: 'AI मदत',
    nav5: 'प्रोफाइल',
    fwTitle: 'कामगार शोधा',
    regTitle: 'कामगार म्हणून नोंदणी',
    regBtn: '✅ आत्ता नोंदणी करा',
    regLblName: '👤 तुमचे पूर्ण नाव',
    regLblPhone: '📞 मोबाइल नंबर',
    regLblTrade: '🛠 तुमचे काम / कौशल्य',
    regLblExp: '📅 अनुभव (वर्षे)',
    regLblArea: '📍 तुमचा परिसर',
    regLblWage: '💰 दैनंदिन मजुरी (₹)',
    regLblLang: '🗣 तुम्ही कोणत्या भाषा बोलता',
    pjTitle: 'काम पोस्ट करा',
    pjLblTitle: '📋 कामाचे नाव',
    pjLblTrade: '🛠 कोणता कामगार हवा',
    pjLblDesc: '📝 कामाचे वर्णन',
    pjLblLoc: '📍 ठिकाण',
    pjLblWage: '💰 मजुरी (₹/दिवस)',
    pjLblPhone: '📞 तुमचा नंबर',
    pjLblUrgent: '🔴 हे तातडीचे आहे का?',
    aiTitle: '🤖 AI सहाय्यक',
    aiIntro: 'काहीही विचारा — मजुरी, हक्क, काम कसे शोधावे…',
    aiQuickLbl: 'झटपट प्रश्न',
    mpTitle: 'माझे प्रोफाइल',
    voiceSpeak: 'बोलून फॉर्म भरा',
    voiceListening: '🔴 ऐकतोय… बोला',
    wagePer: 'दररोज',
    callBtn: '📞 फोन करा',
    hireBtn: '✅ काम द्या',
    appliedBtn: 'अर्ज केला',
    applyBtn: 'कामासाठी अर्ज करा',
    availNow: 'आत्ता उपलब्ध',
    availSoon: 'उद्यापासून',
    availBusy: 'व्यस्त',
    verified: '✓ सत्यापित',
    quickQs: [
      'प्लंबरची किमान मजुरी किती?',
      'आधार कार्ड कसे काढावे?',
      'नोंदणीसाठी कोणते कागद लागतात?',
      'मजुरी न मिळाल्यास काय करावे?',
    ]
  }
};

export const TRADES = [
  { icon: '🔧', name: 'Plumber', hi: 'प्लंबर', mr: 'प्लंबर' },
  { icon: '⚡', name: 'Electrician', hi: 'इलेक्ट्रीशियन', mr: 'इलेक्ट्रिशियन' },
  { icon: '🪚', name: 'Carpenter', hi: 'बढ़ई', mr: 'सुतार' },
  { icon: '🎨', name: 'Painter', hi: 'पेंटर', mr: 'रंगारी' },
  { icon: '🧱', name: 'Mason', hi: 'राजमिस्त्री', mr: 'गवंडी' },
  { icon: '🔩', name: 'Welder', hi: 'वेल्डर', mr: 'वेल्डर' },
  { icon: '🏗', name: 'Helper', hi: 'मजदूर', mr: 'मजूर' },
  { icon: '🍳', name: 'Cook', hi: 'रसोइया', mr: 'स्वयंपाकी' },
  { icon: '🚛', name: 'Driver', hi: 'ड्राइवर', mr: 'ड्रायव्हर' },
  { icon: '🌿', name: 'Gardener', hi: 'माली', mr: 'माळी' }
];

export const AVATAR_COLORS = [
  '#F05A1A',
  '#16A34A',
  '#1D6FB8',
  '#7C3AED',
  '#DC2626',
  '#D97706',
  '#0891B2',
  '#059669'
];
